# DyberVPN Test Client Configuration (PQ-Only Mode)
# Copyright 2026 Dyber, Inc.
#
# Generate real keys with: dybervpn genkey -m pqonly
# DO NOT use placeholder values in production.

[interface]
name = "dvpn1"
private_key = "REPLACE_WITH_YOUR_X25519_PRIVATE_KEY"
pq_private_key = "REPLACE_WITH_YOUR_MLKEM768_PRIVATE_KEY"
mldsa_private_key = "REPLACE_WITH_YOUR_MLDSA65_PRIVATE_KEY"
address = "10.200.200.2/24"
mode = "pqonly"

[[peer]]
public_key = "REPLACE_WITH_SERVER_X25519_PUBLIC_KEY"
pq_public_key = "REPLACE_WITH_SERVER_MLKEM768_PUBLIC_KEY"
mldsa_public_key = "REPLACE_WITH_SERVER_MLDSA65_PUBLIC_KEY"
allowed_ips = "10.200.200.0/24"
endpoint = "127.0.0.1:51820"
persistent_keepalive = 25
