# DyberVPN Test Client Configuration
# Copyright 2026 Dyber, Inc.
#
# Generate real keys with: dybervpn genkey -m hybrid
# DO NOT use placeholder values in production.

[interface]
name = "dvpn1"
private_key = "REPLACE_WITH_YOUR_X25519_PRIVATE_KEY"
pq_private_key = "REPLACE_WITH_YOUR_MLKEM768_PRIVATE_KEY"
address = "10.0.0.2/24"
mode = "hybrid"

[[peer]]
public_key = "REPLACE_WITH_SERVER_X25519_PUBLIC_KEY"
pq_public_key = "REPLACE_WITH_SERVER_MLKEM768_PUBLIC_KEY"
allowed_ips = "10.0.0.0/24"
endpoint = "127.0.0.1:51820"
persistent_keepalive = 25
